namespace ColoniaHormigas
{
	public enum EnumEstado
	{
		VACIO = 0,
		HORMIGA = 1,
		COMIDA = 2,
		HORMIGA_CON_COMIDA = 3,
		FEROMONA = 4,
		FEROMONA_OPTIMA = 5,
		HORMIGA_ENRUTADA_HACIA_OBJETIVO = 6,
		HORMIGA_ENRUTADA_HACIA_COLONIA = 7,
		COLONIA = 8
	}
}